name: my_portfolio
description: "portfolio flutter web project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Rive 버전 강제를 위해 ^ 제거 (Overrides와 동일하게 맞춤)
  rive: 0.14.0-dev.13
  rive_native: 0.0.16

  # 들여쓰기 확실하게 맞춤
  go_router: ^17.0.0
  scroll_to_index: ^3.0.1
  gap: ^3.0.1
  flutter_animate: ^4.5.2

  vector_graphics: ^1.1.18
  http: ^1.6.0
  envied: ^1.1.1
  flutter_layout_grid: ^2.0.8
  font_awesome_flutter: ^10.12.0
  forge2d: ^0.14.2+1
  url_launcher_web: ^2.4.1

# rive 버전 강제
# (dev.14 버전 rive_native 호환성 문제가 존재함)
dependency_overrides:
  rive: 0.14.0-dev.13
  rive_native: 0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  vector_graphics_compiler: ^1.1.16
  build_runner: ^2.5.4
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true

  fonts:
    - family: Noto_Sans
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400


  assets:
    - path: assets/icon/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/skill/
      transformers:
        - package: vector_graphics_compiler

    - assets/rive/
