name: my_portfolio
description: "portfolio flutter web project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">= 3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rive: ^0.14.0-dev.13
  rive_native: ^0.0.16

# rive 버전 강제
# (dev.14 버전 rive_native 호환성 문제가 존재함)
dependency_overrides:
  rive: 0.14.0-dev.13
  rive_native: 0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rive/
