name: font_kit
description: 'font kit'
version: 1.0.0
resolution: workspace

executables:
  font_kit:

environment:
  sdk: ^3.10.1

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
