name: font_kit
description: 'font kit'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  path: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
