name: 포트폴리오 웹 배포

on:
  push:
    # 실행할 기본 브랜치
    branches: [ "main" ]
  # GitHub Actions 탭에서 수동으로 이 워크플로우를 실행할 수 있음
  workflow_dispatch:

# 이 동시성 설정은 GitHub Pages에 대한 배포 작업이 동시에 여러 개 실행되지 않도록 제한
# 이미 실행 중인 배포 작업이 완료될 때까지 기다림
concurrency:
  group: "pages"
  # 현재 진행 중인 작업을 취소하지 않음
  cancel-in-progress: false

env:
  PATH_TO_APP: my_portfolio

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        # 레포지토리의 코드를 가져옵니다.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_KEY }}
          submodules: true

      - name: 파이썬 셋업
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 파이썬 종속성 설치
        run: |
          python -m pip install --upgrade pip
          pip install fonttools brotli

      - name: 플러터 환경 설정
        # 플러터 환경을 설정합니다.
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: 3.38.3

      - name: 페이지 설정
        id: pages
        # GitHub Pages 설정을 구성합니다.
        # 기본 경로를 출력 변수로 제공합니다.
        uses: actions/configure-pages@v5

      - name: 종속성 설치
        run: flutter pub get

      - name: 웹 빌드
        run: flutter build web --release --base-href "${{ steps.pages.outputs.base_path }}/"

#      - name: Run tests
         # 애플리케이션의 테스트를 실행합니다.
#        run: flutter test

      - name: 빌드 아티팩트 업로드
        # 빌드된 웹 아티팩트를 업로드합니다.
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  continuous-deployment:
    name: Continuous Deployment
    needs: continuous-integration
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 웹 배포
        id: deployment
        uses: actions/deploy-pages@v4